{
    "name": "Construction Master Catalog",
    "version": "19.0.1.0.0",
    "category": "Construction",
    "summary": "Catálogos maestros de conceptos, insumos, unidades, rendimientos, cuadrillas y plantillas",
    "author": "Open Source Integrators, Odoo Community Association (OCA)",
    "website": "https://github.com/OCA/vertical-construction",
    "development_status": "Beta",
    "license": "LGPL-3",
    "depends": [
        "product",
        "stock",
        "purchase",
        "report_xlsx",
        "auditlog",
    ],
    "data": [
        "security/construction_catalog_security.xml",
        "security/ir.model.access.csv",
        "data/ir_sequence_data.xml",
        "views/catalog_version_views.xml",
        "views/catalog_concept_views.xml",
        "views/catalog_input_views.xml",
        "views/catalog_uom_views.xml",
        "views/catalog_yield_views.xml",
        "views/catalog_crew_views.xml",
        "views/catalog_template_views.xml",
        "views/catalog_snapshot_views.xml",
        "views/product_product_views.xml",
        "views/construction_catalog_menus.xml",
        "wizards/catalog_version_copy_views.xml",
    ],
    "demo": [
        "demo/construction_catalog_version_demo.xml",
        "demo/construction_catalog_concept_demo.xml",
        "demo/construction_catalog_input_demo.xml",
        "demo/construction_catalog_crew_demo.xml",
        "demo/construction_catalog_crew_line_demo.xml",
        "demo/construction_catalog_yield_demo.xml",
        "demo/construction_catalog_template_demo.xml",
        "demo/construction_catalog_template_line_demo.xml",
    ],
    "application": True,
    "installable": True,
}
