{
    "name": "Construction Budget APU",
    "version": "19.0.1.0.0",
    "category": "Construction",
    "summary": (
        "Presupuestos de obra con APU, capítulos, partidas, versiones y comparativos"
    ),
    "author": "Open Source Integrators, Odoo Community Association (OCA)",
    "website": "https://github.com/OCA/vertical-construction",
    "development_status": "Beta",
    "license": "LGPL-3",
    "depends": [
        "sale",
        "project",
        "analytic",
        "account",
        "account_budget_oca",
        "account_analytic_required",
        "report_xlsx",
        "auditlog",
        "web_export_view",
    ],
    "data": [
        "security/construction_budget_security.xml",
        "security/ir.model.access.csv",
        "data/ir_sequence_data.xml",
        "views/construction_budget_views.xml",
        "views/construction_budget_version_views.xml",
        "views/construction_budget_chapter_views.xml",
        "views/construction_budget_line_views.xml",
        "views/construction_budget_apu_views.xml",
        "views/crossovered_budget_views.xml",
        "views/construction_budget_menus.xml",
        "wizards/budget_version_approve_views.xml",
        "wizards/budget_version_compare_views.xml",
        "report/construction_budget_report.xml",
    ],
    "demo": [
        "demo/construction_budget_demo.xml",
    ],
    "application": True,
    "installable": True,
    "post_init_hook": "construction_budget_apu.hooks._post_init_hook",
}
